### ISSUE TITLE
When enter token, takes me to discord normal account login page

### ISSUE THREAD

**Issue by Derpiebeast** [Flam3rboy/discord-bot-client#195] opened 2020-12-05 17:35 UTC
![image_2020-12-05_183532](https://user-images.githubusercontent.com/68738452/101259353-a7e5b200-3728-11eb-989f-098362e8b674.png)

**Comment by Flam3rboy** [comment] 2020-12-05 22:25
duplicate of #158

**Closed by Flam3rboy** 2020-12-05 22:25 UTC
