### ISSUE TITLE
Members do not load

### ISSUE THREAD

**Issue by SracccGames** [Flam3rboy/discord-bot-client#276] opened 2021-07-07 03:05 UTC
members do not load so you cant see who is in discord.
![2021-07-06](https://user-images.githubusercontent.com/83980971/124694108-a17e0b00-deae-11eb-9a35-8b7935548e92.png)

**Comment by TrueVulpis** [comment] 2021-07-07 07:07
Your bot application needs to have "Server Member Intents" turned on. You'll find it under the bot section, it's the 4th button down. 
![image](https://user-images.githubusercontent.com/81141083/124714986-c96c7d80-df45-11eb-9793-a148b159a6ae.png)

**Comment by LIGHT-RIDER** [comment] 2021-07-07 10:41
O

**Comment by Flam3rboy** [comment] 2021-07-07 13:24
duplicate of #144

**Closed by Flam3rboy** 2021-07-07 13:24 UTC

**Comment by SracccGames** [comment] 2021-07-07 14:49
i dont see the bot section

**Comment by SracccGames** [comment] 2021-07-07 14:58
i turned on same thing.

**Comment by SracccGames** [comment] 2021-07-07 15:02
> Your bot application needs to have "Server Member Intents" turned on. You'll find it under the bot section, it's the 4th button down.
> ![image](https://user-images.githubusercontent.com/81141083/124714986-c96c7d80-df45-11eb-9793-a148b159a6ae.png)

i did turn on

**Comment by SracccGames** [comment] 2021-07-07 15:18
still #144 is happening when i turn on settings.

**Comment by Flam3rboy** [comment] 2021-07-08 07:42
> still #144 is happening when i turn on settings.

yes because its a bug
