### ISSUE TITLE
No members in BotClient

### ISSUE THREAD

**Issue by TillDV** [Flam3rboy/discord-bot-client#236] opened 2021-03-01 09:41 UTC
I can't see users in the right bar!
![Bild_2021-03-01_104049](https://user-images.githubusercontent.com/67326844/109479351-950a2180-7a7a-11eb-9e2e-febc3a90fc24.png)

**Comment by Flam3rboy** [comment] 2021-03-01 09:41
duplicate of #144

**Closed by Flam3rboy** 2021-03-01 09:41 UTC
