### ISSUE TITLE
Broken member list

### ISSUE THREAD

**Issue by NewLife1324** [Flam3rboy/discord-bot-client#261] opened 2021-05-14 04:49 UTC
![image](https://user-images.githubusercontent.com/61694357/118222680-b62ebb80-b488-11eb-8e75-2a57ddccf0e4.png)
For each role, N users are shown who are actually online, but discord shows another user instead of one, even if it is offline. He just swapped the users

**Comment by Flam3rboy** [comment] 2021-05-14 04:59
duplicate of #144

**Closed by Flam3rboy** 2021-05-14 04:59 UTC
