### ISSUE TITLE
Cant see users in the side bar and cant logout

### ISSUE THREAD

**Issue by kaytitulaer2008** [Flam3rboy/discord-bot-client#265] opened 2021-06-07 11:00 UTC
the side bar where you normaly see users just stays empty. there is 1 thing there, the thing that you see when the users are loading, and thats the bot thats loading. and i cant logout to login on another bot

**Comment by Flam3rboy** [comment] 2021-06-07 11:14
Duplicate of #144

**Closed by Flam3rboy** 2021-06-07 11:14 UTC
