### ISSUE TITLE
cant see any msges

### ISSUE THREAD

**Issue by AMTitan** [Flam3rboy/discord-bot-client#255] opened 2021-04-30 14:10 UTC
![image](https://user-images.githubusercontent.com/29708070/116706967-2d9a2080-a99c-11eb-853c-3100005e6738.png)
node v : 15.14.0
latest version of github as of apr 30 10am est

**Comment by Flam3rboy** [comment] 2021-04-30 14:11
duplicate of #144

**Closed by Flam3rboy** 2021-04-30 14:11 UTC
