### ISSUE TITLE
Member List

### ISSUE THREAD

**Issue by therealOri** [Flam3rboy/discord-bot-client#36] opened 2020-08-09 00:12 UTC
The member list on the right side never loads :/
![Not_loading](https://user-images.githubusercontent.com/45724082/89722074-3841ff00-d9a2-11ea-8b28-7ec9a3a941f0.jpg)

And the cool badges aren't viewable by normal/other accounts.
![No_Badges](https://user-images.githubusercontent.com/45724082/89722080-5445a080-d9a2-11ea-97e9-50bd6fe67c7b.jpg)

I reloaded and refreshed everything more than 5 times now and still nothing. (If I wanted to use a bot to talk with then I'd use Targo. But I'd love to use this because it promised cool badges and stuff from videos of what I've seen.)

**Comment by Assfugil** [comment] 2020-08-09 06:23
Do you have the guild member intent enabled?

**Comment by PiauTW** [comment] 2020-08-09 11:22
have same problem
![image](https://user-images.githubusercontent.com/46679502/89730921-a9061b80-da75-11ea-8d30-e26256cf37e8.png)

**Comment by Flam3rboy** [comment] 2020-08-09 14:10
duplicate of #8

**Closed by Flam3rboy** 2020-08-09 14:10 UTC
