### ISSUE TITLE
Can't see member list

### ISSUE THREAD

**Issue by Nicky715** [Flam3rboy/discord-bot-client#136] opened 2020-09-28 16:02 UTC
The member list seems to show up as empty whenever I am on a server and it will not show anybody who is in the server.
![image](https://user-images.githubusercontent.com/56802810/94457387-81345980-0182-11eb-842d-46a219743703.png)

**Comment by Maxnflaxl1O** [comment] 2020-09-29 15:09
same with me

**Comment by Flam3rboy** [comment] 2020-10-06 17:48
duplicate of #144

**Closed by Flam3rboy** 2020-10-06 17:48 UTC
