### ISSUE TITLE
Problem

### ISSUE THREAD

**Issue by p9sq** [Flam3rboy/discord-bot-client#210] opened 2021-01-08 03:03 UTC
I don't know if it's just me, but when I run Discord Bot Client on my pc, it takes ages to load

**Comment by Flam3rboy** [comment] 2021-01-08 11:09
duplicate of #144

**Comment by Flam3rboy** [comment] 2021-01-08 11:11
thats normal, because it needs to patch the source files on the fly

**Closed by Flam3rboy** 2021-01-08 11:11 UTC
