### ISSUE TITLE
[Suggestion] Add embed messages.

### ISSUE THREAD

**Issue by BuilderHD** [Flam3rboy/discord-bot-client#196] opened 2020-12-08 12:18 UTC
I'm bot but i can't send embed message)
The developer of this client, i hope you can do it!

**Comment by Dark42ed** [comment] 2020-12-08 15:50
Dupe of #167

**Comment by BuilderHD** [comment] 2020-12-08 16:30
i am trying to make

**Comment by Flam3rboy** [comment] 2020-12-08 18:39
nice 👍 
I'll close this issue but will keep #167 open

**Closed by Flam3rboy** 2020-12-08 18:39 UTC
