### ISSUE TITLE
Too Many Bugs

### ISSUE THREAD

**Issue by PyYakro** [Flam3rboy/discord-bot-client#188] opened 2020-11-28 09:58 UTC
I found several bugs that are very annoying. All bugs in the screenshots:

#1 The list of channel members disappeared. Tried to fix it by enabling / disabling the "Server Members Intent" item in the Discord Developers Portal.

![Screenshot#1](https://user-images.githubusercontent.com/57525376/100499049-237bb800-3199-11eb-80b1-25d718ec7c75.jpg)

#2 Dialogues with other users are not loaded after launch. Also restarting the program does not help.

![Снимок экрана (5)_LI](https://user-images.githubusercontent.com/57525376/100499220-48bcf600-319a-11eb-95d5-cf65c0a26b81.jpg)

#3 After you have left the voice channel, you still remain in it.

![Снимок экрана (6)_LI](https://user-images.githubusercontent.com/57525376/100499254-933e7280-319a-11eb-8626-74abe73cbf8f.jpg)

P.S. I don't know much English. I tried to describe the bugs as much as possible.

**Comment by Flam3rboy** [comment] 2020-11-28 12:09
the first issue is a duplicate of #168 
the second one is intentional, because discord doesn't load the latest DM list
and the third one is known

**Closed by Flam3rboy** 2020-11-28 12:09 UTC
