### ISSUE TITLE
Large bots that need sharding happens to load indefinitely instead of loading first shard, Feature Idea for Large Bots

### ISSUE THREAD

**Issue by grifgrif** [Flam3rboy/discord-bot-client#177] opened 2020-11-08 14:12 UTC
**Issue**
Large bots that need sharding happens to load indefinitely instead of loading first shard.
![Load Image](https://user-images.githubusercontent.com/47899313/98467178-463b3200-21d4-11eb-9b69-24f7480cc4bc.png)

**Feature Ideas**
Add research by Server ID.
See only a list of ServerID, list that you can configure on the settings.
Choose to request or not server icons.

**Comment by grifgrif** [comment] 2020-11-08 14:19
Different from Issue #86
You can't disconnect while this loading and moreover it's a feature request.

**Comment by AwxyyDeveloper** [comment] 2020-12-04 02:58
@grifgrif
Suggesting future ideas is not going to do anything. The developer has stopped working on this project and it has from now been discontinued. You just got to live with it.

**Comment by Flam3rboy** [comment] 2021-04-03 16:57
duplicate of #86

**Closed by Flam3rboy** 2021-04-03 16:57 UTC
