### ISSUE TITLE
can't open on mac

### ISSUE THREAD

**Issue by Lanaaaaaaa** [Flam3rboy/discord-bot-client#127] opened 2020-09-17 06:05 UTC
please help me,, i can't open on my masOS Catalina version 10.15.6
please help me.

**Comment by Lanaaaaaaa** [comment] 2020-09-17 06:06
@Flam3rboy

**Comment by Daniellop1** [comment] 2020-09-17 09:49
read #118

**Comment by Flam3rboy** [comment] 2020-09-17 19:52
duplicate of #118

**Closed by Flam3rboy** 2020-09-17 19:52 UTC
