### ISSUE TITLE
Can't see server members

### ISSUE THREAD

**Issue by Dellafj911** [Flam3rboy/discord-bot-client#168] opened 2020-10-28 13:10 UTC

**Comment by keatonbuilder** [comment] 2020-10-28 19:52
This is just the Discord Bot API as bots see server members differently than a normal user.

**Comment by grifgrif** [comment] 2020-11-08 14:23
You need to check this to request User List
![mRP 1](https://user-images.githubusercontent.com/47899313/98467556-476d5e80-21d6-11eb-8306-5c2e469ca68e.png)

**Comment by Flam3rboy** [comment] 2020-11-28 12:08
also its a bit buggy, don't expect it to load the member list

**Comment by BuilderHD** [comment] 2020-12-09 16:39
We trying to fix this.

**Comment by joebyjo** [comment] 2021-01-16 06:36
Its not the Server Member Intent,My bot has the permission and still cant see

**Comment by RBXCommunity** [comment] 2021-01-31 23:33
We Cant See The Members List Cant U Just Make An Copy Of The Discord App?

**Comment by Flam3rboy** [comment] 2021-02-01 06:40
I'm in fact doing this: https://github.com/discord-open-source

**Comment by Flam3rboy** [comment] 2021-04-03 16:58
duplicate of #144

**Closed by Flam3rboy** 2021-04-03 16:58 UTC
