### ISSUE TITLE
Console errors and white screen 

### ISSUE THREAD

**Issue by WildThunder4764** [Flam3rboy/discord-bot-client#189] opened 2020-11-29 16:06 UTC
i opened the inspect panel and got this in the console windows is white same error when opening index.html in chrome
![image](https://user-images.githubusercontent.com/71690286/100547006-78e3c200-328a-11eb-8bb9-90db7e685d06.png)
window looks like this 
![image](https://user-images.githubusercontent.com/71690286/100547025-9dd83500-328a-11eb-8801-09e42cbd11a9.png)
tried reloading pls help i have node i also tried the exe file on windows and npm start after installing dependencies from config.json using npm i know programming i can make changes to code if you want just tell me what to do

**Comment by Flam3rboy** [comment] 2020-11-29 20:37
the bot client doesn't work in the browser and the white screen is a duplicate of #161

**Closed by Flam3rboy** 2020-11-29 20:37 UTC
