### ISSUE TITLE
Can't open on mac

### ISSUE THREAD

**Issue by F1R3L1GHT** [Flam3rboy/discord-bot-client#145] opened 2020-10-06 15:54 UTC
ok so i updated my mac. before i updated i could still use it. now it says Discord Bot Client Cannot be opened. help lmao

**Comment by Flam3rboy** [comment] 2020-10-06 17:49
its a known issue, build it yourself and if anyone manage to make a working a executable

**Comment by Flam3rboy** [comment] 2020-10-24 10:39
duplicate of #165

**Closed by Flam3rboy** 2020-10-24 10:39 UTC
