### ISSUE TITLE
Doesn't work on mac

### ISSUE THREAD

**Issue by HZ-0Z3R0** [Flam3rboy/discord-bot-client#192] opened 2020-12-02 11:43 UTC
It just auto quits when I open it.

**Comment by Cloudfry** [comment] 2020-12-02 12:58
same it doesn't even opens for me

**Comment by AwxyyDeveloper** [comment] 2020-12-04 02:53
Hm, this issue is not normal. It should be working. Is there any other message that comes after the application automatically quitting?

**Comment by Flam3rboy** [comment] 2020-12-04 18:58
duplicate of #165

**Closed by Flam3rboy** 2020-12-04 18:58 UTC
