### ISSUE TITLE
Can't open on mac

### ISSUE THREAD

**Issue by IncogVibes** [Flam3rboy/discord-bot-client#193] opened 2020-12-02 20:05 UTC
<img width="261" alt="Screen Shot 2020-12-02 at 12 04 57 PM" src="https://user-images.githubusercontent.com/68030441/100925244-98e7d100-3496-11eb-8fcc-90363d1e3eb0.png">
always shows this when i wanna open it, dont know if its just me or what

**Comment by Axo-The-Lord** [comment] 2020-12-04 01:16
It's probably just you. I have a Mac and the only problem I've had is that _I literally can't open the client without it crashing._ I can bypass the security measures but it crashes for some reason. Please, please fix. If you need I can send a log.

**Comment by AwxyyDeveloper** [comment] 2020-12-04 02:53
I'm not sure about this. But I think that Discord Bot Client isn't supposed to be running on a Mac device. It should work. Does your computer account have Administrator permissions? If not you cannot run this application.

**Comment by Flam3rboy** [comment] 2020-12-04 18:58
duplicate of #165

**Closed by Flam3rboy** 2020-12-04 18:58 UTC
