### ISSUE TITLE
Doesn't trust

### ISSUE THREAD

**Issue by HannasaurusRex** [Flam3rboy/discord-bot-client#164] opened 2020-10-21 00:08 UTC
I tried opening it but I'm on Mac and it says "Can't be opened because Apple cannot check for malicious software" can you help me with this? And I don't exactly know what you mean or know how to when you say you can build it yourself.

**Comment by DarrenAlex** [comment] 2020-10-21 14:38
Build it yourself OR get the mac developer license.

**Comment by Flam3rboy** [comment] 2020-10-21 14:39
duplicate of #151

**Closed by Flam3rboy** 2020-10-21 14:39 UTC
