### ISSUE TITLE
Can't see messages, send messages or users

### ISSUE THREAD

**Issue by MostlyBananas** [Flam3rboy/discord-bot-client#223] opened 2021-02-04 13:09 UTC
I can't see the messages, nor the users, or the channel history. I can type stuff in but it doesn't register I'm doing so and when I hit enter, it disappears and nothing happens. If a new message is sent, it says "1 new message, mark as read" but nothing is there and clicking it does nothing either. It says "load messages" but if I click this it loads for a few seconds and then goes back to how it was.
What is happening and how do I fix it??

**Comment by Flam3rboy** [comment] 2021-02-04 15:21
duplicate of #144

**Closed by Flam3rboy** 2021-02-04 15:21 UTC
